solution/course/config/urls.py
from django.contrib import admin
from django.urls import path, include

from notes.views import redirect_to_note_detail
from common.views import LoginView, LogoutView

from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="common/home.html"), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('<int:note_id>/', redirect_to_note_detail, name="redirect-to-note-detail"),
    path('notes/', include("notes.urls", namespace="notes")),
    path('todo/', include("todo.urls", namespace="todo")),
]

solution/course/todo/urls.py
"""ToDo URL Configuration."""
from django.urls import path

from todo.views import TodoDetails

app_name = "todo"
urlpatterns = [
    path('<int:todo_id>/', TodoDetails.as_view(), name="details"),
]

solution/course/common/models.py
"""Data for the common views"""
from config.store import CustomStore
from django.contrib.auth.hashers import make_password


class UserStore(CustomStore):
    """Store for the users."""

    model_name = "users"
    backup = [
        {
            "name": "admin",
            "password": make_password("admin"),
            "role": "admin",
            "voted_notes": []
        },
        {
            "name": "james",
            "password": make_password("hendrix"),
            "role": "editor",
            "voted_notes": []
        },
        {
            "name": "fred",
            "password": make_password("baggins"),
            "role": "user",
            "voted_notes": []
        },
        {
            "name": "ganesh",
            "password": make_password("the_grey"),
            "role": "user",
            "voted_notes": []
        }
    ]

solution/course/common/forms.py
"""Common forms to various apps."""

from django import forms


class LoginForm(forms.Form):
    """A simple login form."""

    user_name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

solution/course/common/views.py
"""Common views of the website."""
from django.views.generic.edit import FormView
from django.views.generic import View
from django.contrib.auth.hashers import check_password
from django.urls import reverse
from django.shortcuts import redirect

from common.forms import LoginForm
from common.models import UserStore


store = UserStore()
users = store.get()


class LogoutView(View):
    """Log out the user."""

    def get(self, request):
        """Log out and redirect."""
        request.session.flush()
        return redirect("home")


class LoginView(FormView):
    """Form view for the user log in feature."""

    template_name = "common/login.html"
    form_class = LoginForm
    success_url = "/login/"

    def get(self, request):
        """Test."""
        if request.session.get("user_name", None):
            return redirect("home")
        return super().get(request)

    def form_valid(self, form):
        """Check the credentials."""
        user_name = form.data.get("user_name")
        password = form.data.get("password")
        for user in users:
            if user["name"] == user_name and check_password(password, user["password"]):
                self.request.session["user_name"] = user_name
                self.request.session["user_votes"] = user["voted_notes"]
                self.request.session["user_can_write_notes"] = user["role"] in ("admin", "editor")
                break
        return super().form_valid(form)

    def get_success_url(self):
        """Redirect the user to the home if the authentication worked."""
        if self.request.session.get("user_name", None):
            return reverse("home")
        return super().get_success_url()

solution/course/common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My website</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <header>
      <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'notes:home' %}">My Course Notes</a></li>
        <li><a href="{% url 'todo:details' todo_id=1 %}">My ToDo List</a></li>
        <li>
          {% if request.session.user_name %}
          Logged in as {{request.session.user_name }}.
          <a href="{% url 'logout' %}">Log out</a>
          {% else %}
          <a href="{% url 'login' %}">Log in</a>
          {% endif %}
        </li>
      </ul>
    </header>
    <section>
      {% block content %}
      {% endblock %}
    </section>
    <footer>
      &copy; to me. Look mom, I am already using cookies!
    </footer>
  </body>
</html>

solution/course/common/templates/common/home.html
{% extends 'common/base.html' %}

{% block content %}
<h1>Welcome to my new website!</h1>
<p>Feel free to browse through my notes or check my To Do list using the menu on the top.</p>
{% endblock %}

solution/course/common/templates/common/login.html
{% extends 'common/base.html' %}

{% block content %}
  <h1>User Authentication</h1>
  <form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button>Submit</button>
  </form>
{% endblock %}