solution/course/config/urls.py
from django.contrib import admin
from django.urls import path, include

from notes.views import redirect_to_note_detail
from common.views import LoginView, LogoutView

from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="common/home.html"), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
    path('<int:note_id>/', redirect_to_note_detail, name="redirect-to-note-detail"),
    path('notes/', include("notes.urls", namespace="notes")),
    path('todo/', include("todo.urls", namespace="todo")),
]

solution/course/notes/urls.py
"""Notes URL Configuration."""
from django.urls import path
from django.views.generic import TemplateView

from notes.views import (AddNoteView, EditNoteView, NoteDetails,
                         NotesBySection, SearchView, SectionList, VoteNoteView,
                         home)

app_name = "notes"
urlpatterns = [
    path('', home, name="home"),
    path('sections/', SectionList.as_view(), name="sections"),
    path('sections/<section_name>/', NotesBySection.as_view(), name="by_section"),
    path('<int:note_id>/', NoteDetails.as_view(), name="details"),
    path('<int:note_id>/edit/', EditNoteView.as_view(), name="edit"),
    path('<int:note_id>/vote/', VoteNoteView.as_view(), name="vote"),
    path('search/', SearchView.as_view(), name="search"),
    path('add/ok', TemplateView.as_view(template_name="notes/note_added.html"), name="added_ok"),
    path('add/', AddNoteView.as_view(), name="add"),
]

solution/course/todo/urls.py
"""ToDo URL Configuration."""
from django.urls import path

from todo.views import TodoDetails

app_name = "todo"
urlpatterns = [
    path('<int:todo_id>/', TodoDetails.as_view(), name="details"),
]

solution/course/notes/models.py
"""Data for the notes views"""
from config.store import CustomStore


class NoteStore(CustomStore):
    """Store for the notes."""

    model_name = "notes"
    backup = [
        {
            "text": "Web frameworks are a way to improve our productivity and make complex things look easy.",
            "section": "Web Frameworks",
            "votes": 0
        },
        {
            "text": "Django is a web framework written with Python that offers a 'batteries included' approach, as opposed to Flask, that aims at minimizing the initial features to reduce the footprint.",
            "section": "Web Frameworks",
            "votes": 0
        },
        {
            "text": "Most web frameworks use the MVC design pattern that states that logic, data and visualization should be kept in different places.",
            "section": "Web Frameworks",
            "votes": 0
        },
        {
            "text": "Setting up Django is very simple. It requires installing Django, starting a project and an app.",
            "section": "Setting up Django",
            "votes": 0
        },
        {
            "text": "The startproject command lets us specify the directory where the project will be created.",
            "section": "Setting up Django",
            "votes": 0
        },
        {
            "text": "Django comes with a development web server that makes it very simple to install and start working.",
            "section": "Setting up Django",
            "votes": 0
        },
        {
            "text": "URL Mapping can be very easy at the beginning but it may become extremely complex in some cases.",
            "section": "URL Mapping",
            "votes": 0
        },
        {
            "text": "URL endpoints may be defined with literals and parameters, which will be passed on to the view.",
            "section": "URL Mapping",
            "votes": 0
        },
        {
            "text": "Parameters passed with the <b><</b> and <b>></b> will be passed as keyword arguments.",
            "section": "URL Mapping",
            "votes": 0
        },
    ]

solution/course/notes/forms.py
"""Forms for the notes app."""

from django import forms

SECTIONS = (
    (None, "-- Any --"),
    ("Web Frameworks", "Web Frameworks"),
    ("Setting up Django", "Setting up Django"),
    ("URL Mapping", "URL Mapping"),
)


class SearchForm(forms.Form):
    """A simple search form."""

    term_of_search = forms.CharField()
    section = forms.ChoiceField(choices=SECTIONS, required=False)


class AddNoteForm(forms.Form):
    """A form to add new notes."""

    section = forms.ChoiceField(choices=SECTIONS)
    text = forms.CharField(widget=forms.Textarea())


class EditNoteForm(forms.Form):
    """A form to edit note texts."""

    section = forms.ChoiceField(choices=SECTIONS, disabled=True)
    text = forms.CharField(widget=forms.Textarea())

solution/course/notes/views.py
"""Views for the notes app."""
from django.template.loader import get_template
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.views import View

from notes.models import NoteStore
from common.models import UserStore
from notes.forms import SearchForm, AddNoteForm, EditNoteForm


store = NoteStore()
notes = store.get()


def redirect_to_note_detail(request, note_id):
    """Redirect to the note details view."""
    return redirect(reverse("notes:details", args=[note_id]))


def home(request):
    """Home for my notes app."""
    template = get_template("notes/home.html")
    context = {
        "request": request,
        "title": "Welcome to my course notes!",
        "links": [
            {
                "url": reverse("notes:sections"),
                "label": "Check the list of sections"
            },
            {
                "url": reverse("notes:details", args=[1]),
                "label": "Read my first notes"
            },
            {
                "url": reverse("notes:search"),
                "label": "Search a note"
            },
            {
                "url": reverse("notes:add"),
                "label": "Add a new note"
            }
        ]
    }
    return HttpResponse(template.render(context))


class SectionList(TemplateView):
    """List of sections."""

    template_name = "notes/sections.html"

    def get_context_data(self):
        """Return the list of sections."""
        return {
            "sections": ["Web Frameworks",
                         "Setting up Django",
                         "URL Mapping"]
            }


class NotesBySection(TemplateView):
    """Show the notes of a section."""

    template_name = "notes/by_section.html"

    def get_context_data(self, section_name):
        """Return the section name and the note list."""
        return {
            "section": section_name,
            "notes": _get_notes_by_section(section_name)
        }


def _get_notes_by_section(section_name):
    """Return the notes of a section."""
    return [note for note in notes
            if note["section"] == section_name]


class SearchView(FormView):
    """The search form view."""

    template_name = "notes/search.html"
    form_class = SearchForm

    def get_context_data(self):
        """Get the notes in the context."""
        term = self.request.GET.get("term_of_search", None)
        section = self.request.GET.get("section", None)
        context = super().get_context_data()
        if term:
            matching = notes
            if section:
                matching = [note for note in notes
                            if note["section"] == section]
            context["notes"] = matching
            context["term_of_search"] = term
            context["section"] = section
        return context


class NoteDetails(TemplateView):
    """Note details."""

    template_name = "notes/details.html"

    def get_context_data(self, note_id):
        """Return the note data."""
        note = notes[note_id - 1]
        return {
            "id": note_id,
            "num_notes": len(notes),
            "note": note
        }


def _get_note_items_matching_search(search_term):
    """Return a list of items with notes marching the search."""
    return [f"<li>{note['text']}</li>" for note in notes
            if search_term.lower() in note["text"].lower()]


class AddNoteView(FormView):
    """Input a new note into the system."""

    template_name = "notes/add.html"
    form_class = AddNoteForm
    success_url = reverse_lazy("notes:added_ok")

    def form_valid(self, *args, **kwargs):
        """Save the note in the store."""
        form = self.get_form()
        note = {
            "text": form.data.get("text", None),
            "section": form.data.get("section", None)
        }
        notes.append(note)
        store.save(notes)
        return super().form_valid(*args, **kwargs)


class EditNoteView(FormView):
    """Edit the text of a note."""

    template_name = "notes/edit.html"
    form_class = EditNoteForm

    def get_initial(self):
        """Return the values of the given note_id."""
        note_id = self.kwargs["note_id"]
        return notes[note_id - 1]

    def get_success_url(self):
        """Return the success url."""
        note_id = self.kwargs["note_id"]
        return reverse("notes:details", args=[note_id])

    def form_valid(self, form):
        """Save the data."""
        note_id = self.kwargs["note_id"]
        notes[note_id - 1]["text"] = form.data.get("text")
        return super().form_valid(form)


class VoteNoteView(View):
    """Store a new vote."""

    def get(self, request, note_id):
        """Store the note vote."""
        # Update the note object
        note = notes[note_id - 1]
        note["votes"] += 1
        store.save(notes)
        # Update the user object
        user_store = UserStore()
        users = user_store.get()
        user_id = None
        for id, user in enumerate(users):
            if user['name'] == request.session.get("user_name"):
                user_id = id
        # user_id = [id for id, user in enumerate(users)
        #            if user["name"] == request.session.get("user_name")].pop(0)
        if user_id is not None:
            users[user_id]["voted_notes"].append(note_id)
            user_store.save(users)
            # Update the session
            request.session["user_votes"] = users[user_id]["voted_notes"]
            return redirect(reverse("notes:details", args=[note_id]))
        else:
            return redirect(reverse("notes:home"))
            

solution/course/notes/templates/notes/add.html
{% extends 'notes/form.html' %}

{% block title %}
  Add a note
{% endblock %}

solution/course/notes/templates/notes/base.html
{% extends 'common/base.html' %}

{% block content %}
<h1>My Notes</h1>
{% endblock %}

solution/course/notes/templates/notes/by_section.html
{% extends 'notes/base.html' %}

{% block content %}
  {{ block.super }}
  <h4>Notes about {{ section }}</h4>
  <ol>
    {% for note in notes %}
      <li>{{ note.text }}</li>
    {% endfor %}
  </ol>
  <p><a href="{% url 'notes:sections' %}">Back to sections</a></p>
{% endblock %}

solution/course/notes/templates/notes/details.html
{% extends 'notes/base.html' %}
{% load sections notes %}

{% block content %}
  {{ block.super }}
  <h4>Note number {{ id }}</h4>
  <p><strong>Section:</strong> {{ note.section|linked_section|safe }}</p>
  <p><strong>Votes:</strong>
    {{ note.votes }}
    {% vote_options request id %}
  </p>
  <p>{{ note.text|safe }}</p>
  <p><a href="{% url 'notes:edit' note_id=id %}">Edit this note</a></p>
  <p>
    {% if id > 1 %}
      <a href="{% url 'notes:details' note_id=id|add:-1 %}">Previous</a>
    {% else %}
      Previous
    {% endif %}
    {% if id < num_notes %}
      <a href="{% url 'notes:details' note_id=id|add:1 %}">Next</a>
    {% else %}
      Next
    {% endif %}
  </p>
{% endblock %}

solution/course/notes/templates/notes/edit.html
{% extends 'notes/form.html' %}

{% block title %}
  Edit a note
{% endblock %}

solution/course/notes/templates/notes/form.html
{% extends 'notes/base.html' %}
{% load sections %}

{% block content %}
  {{ block.super }}
  <h4>{% block title %}Note form{% endblock %}</h4>
  {% if form and request.session.user_name and request.session.user_can_write_notes %}
    <form method="post">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button>Submit</button>
    </form>
  {% else %}
  <p>You are not authorized to access this content. <a href="{% url 'login' %}">Log in</a> to gain access.</p>
  {% endif %}
{% endblock %}

solution/course/notes/templates/notes/home.html
{% extends 'notes/base.html' %}

{% block content %}
 {{ block.super }}
  <h4>{{ title }}</h4>
  <ul>
    {% for link in links %}
      <li><a href="{{ link.url }}">{{ link.label }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

solution/course/notes/templates/notes/note_added.html
{% extends 'notes/base.html' %}

{% block content %}
  {{ block.super }}
  <p>The note was added succesfully!</p>
  <p>Add <a href="{% url 'notes:add' %}">another note</a>.</p>
{% endblock %}

solution/course/notes/templates/notes/search.html
{% extends 'notes/base.html' %}
{% load sections %}

{% block content %}
  {{ block.super }}
  {% if form %}
    <form>
      <table>
        {{ form.as_table }}
      </table>
      <button>Submit</button>
    </form>
  {% endif %}
  {% if notes %}
    <h4>Notes matching <em>{{ term_of_search }}</em>
      {% if section %}
        on section <em>{{ section }}</em>
      {% endif %}
    </h4>
    <ul>
      {% for note in notes %}
        {% if term_of_search in note.text %}
          <li>
            {{ note.text }}.
            <div><em>Filed under section {{ note.section|linked_section|safe }}</em></div>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

solution/course/notes/templates/notes/sections.html
{% extends 'notes/base.html' %}
{% load sections %}

{% block content %}
  {{ block.super }}
  <h4>Browse my notes by section</h4>
  <ol>
    {% for section in sections %}
      <li>{{ section|linked_section|safe }}</li>
    {% endfor %}
  </ol>
{% endblock %}